version: '3.8'
services:
  pg_yellow:
    container_name: pg_yellow
    image: postgres:16
    restart: unless-stopped
    ports:
      - ${DB_YELLOW_PORT}:${DB_YELLOW_PORT}
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./pgdata-yellow:/var/lib/postgresql/data/pgdata
  
  pg_purple:
    container_name: pg_purple
    image: postgres:16
    restart: unless-stopped
    ports:
      - ${DB_PURPLE_PORT}:${DB_PURPLE_PORT}
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      PGDATA: /var/lib/postgresql/data/pgdata
    command: ["postgres", "-p", "${DB_PURPLE_PORT}"]
    volumes:
      - ./pgdata-purple:/var/lib/postgresql/data/pgdata
  
  redis:
    container_name: redis_social
    image: "redis:7.2.4"
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}

  rabbitmq:
    container_name: rabbit_social
    image: rabbitmq:3.13-rc-management
    ports:
      - ${RABBITMQ_PORT_MANAGEMENT}:${RABBITMQ_PORT_MANAGEMENT} # Для веб-интерфейса RabbitMQ
      - ${RABBITMQ_PORT}:${RABBITMQ_PORT}
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
  
  backend:
    container_name: api_nest_1
    build:
      context: ./backend
    depends_on:
      - pg_yellow
      - pg_purple
      - redis
      - rabbitmq
    restart: unless-stopped
    ports:
      - ${API_PORT}:${API_PORT}
    environment:
      API_PORT: ${API_PORT}
      JWT_SECRET: ${JWT_SECRET}
      DB_YELLOW_HOST: pg_yellow
      DB_YELLOW_PORT: ${DB_YELLOW_PORT}
      DB_PURPLE_HOST: pg_purple
      DB_PURPLE_PORT: ${DB_PURPLE_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: ${RABBITMQ_PORT}
      RABBITMQ_PORT_MANAGEMENT: ${RABBITMQ_PORT_MANAGEMENT}
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
      RABBIT_FEED_QUEUE: ${RABBIT_FEED_QUEUE}
      REDIS_HOST: redis
      REDIS_PORT: ${REDIS_PORT}

  feed-ws:
    container_name: feed-ws
    build:
      context: ./feed-ws
    depends_on:
      - pg_yellow
      - pg_purple
      - redis
      - rabbitmq
    restart: unless-stopped
    environment:
      DB_YELLOW_HOST: pg_yellow
      DB_YELLOW_PORT: ${DB_YELLOW_PORT}
      DB_PURPLE_HOST: pg_purple
      DB_PURPLE_PORT: ${DB_PURPLE_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_PORT: ${RABBITMQ_PORT}
      RABBITMQ_PORT_MANAGEMENT: ${RABBITMQ_PORT_MANAGEMENT}
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
      RABBIT_FEED_QUEUE: ${RABBIT_FEED_QUEUE}
      REDIS_HOST: redis
      REDIS_PORT: ${REDIS_PORT}