version: '3.8'
services:
  pg_yellow:
    container_name: pg_yellow
    image: postgres:16
    restart: always
    ports:
      - ${DB_YELLOW_PORT}:5432
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./pgdata-yellow:/var/lib/postgresql/data/pgdata

  pg_blue:
    container_name: pg_blue
    image: postgres:16
    restart: always
    ports:
      - ${DB_BLUE_PORT}:5432
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./pgdata-blue:/var/lib/postgresql/data/pgdata
  
  pg_purple:
    container_name: pg_purple
    image: postgres:16
    restart: always
    ports:
      - ${DB_PURPLE_PORT}:5432
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./pgdata-purple:/var/lib/postgresql/data/pgdata

  # backend:
  #   container_name: api_nest_1
  #   build:
  #     context: ./backend
  #   depends_on:
  #     - pg_yellow
  #   restart: unless-stopped
  #   ports:
  #     - ${API_PORT}:${API_PORT}
  #   environment:
  #     API_PORT: ${API_PORT}
  #     JWT_SECRET: ${JWT_SECRET}
  #     DB_YELLOW_HOST: pg_yellow
  #     DB_YELLOW_PORT: ${DB_YELLOW_PORT}
  #     DB_NAME: ${DB_NAME}
  #     DB_USER: ${DB_USER}
  #     DB_PASSWORD: ${DB_PASSWORD}